[project]
name = "cli-chatbot-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["prompt-toolkit>=3.0.51", "rich>=14.0.0"]

[tool.ruff]
line-length = 88
